routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// TO-DO: Add 'auth' middleware for group below:
Route::middleware([])->group(function() {
	Route::get('profile', 'UserController@profile')->name('profile');
	Route::get('profile/{id}/edit', 'UserController@edit')->name('profile.edit');

	Route::prefix('photos')->name('photos.')->group(function() {
		Route::get('send', 'PhotoController@show_send')->name('send');
		Route::get('receive', 'PhotoController@show_receive')->name('receive');
	});

	Route::get('connections', 'UserController@connections')->name('connections');
});

Route::get('/', function () {
    // return view('welcome');
    return redirect(route('profile'));
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    public function profile()
    {
        $uri = "profile";
        return view('users.index', compact('uri'));
    }

    public function connections()
    {
        $uri = "connections";
        return view('connections.index', compact('uri'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $uri = "profile";
        return view('users.edit', compact('uri'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/edit.blade.php
@extends('layouts.app.index')

@section('content')
  <div class="container p-3 p-lg-5">

    <div class="row">
      {{-- Sidebar --}}
      <div class="col-lg-3">
        @include('components.sidebar')
      </div>
      {{-- Main Content --}}
      <div class="col-lg-9">
        <card-basic title="Edit Profile">
          card
        </card-basic>
      </div>
    </div>

  </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app.index')

@section('content')
  <div class="container p-3 p-lg-5">

    <div class="row">
      {{-- Sidebar --}}
      <div class="col-lg-3">
        @include('components.sidebar')
      </div>
      {{-- Main Content --}}
      <div class="col-lg-9">
        <card-basic title="My Profile">
          {{-- Edit and Delete options --}}
          <template v-slot:options>
            <options-dropdown>

              {{-- Confirm --}}
              <a href="{{ route('profile.edit', ['id' => 1])}}" class="dropdown-item text-primary">
                Edit
              </a>

              {{-- Delete --}}
              <button class="dropdown-item text-danger" type="button"
                data-toggle="modal"
                data-target="#deleteConfirmationModal"
                data-title="Delete Announcement"
                data-action="#">
                Delete
              </button>

            </options-dropdown>
          </template>

          <div class="d-flex align-content-between">
            {{-- Details --}}
            <div class="flex-grow-1">
              {{-- Name --}}
              <div class="form-group">
                <label for="name" class="text-muted">Name</label>
                <p class="lead" id="name">John Doe</p>
              </div>
              {{-- Email --}}
              <div class="form-group">
                <label for="email" class="text-muted">Email Address</label>
                <p class="lead" id="email">john_doe@nasa.app.com</p>
              </div>
            </div>
            {{-- Edit Btn --}}
            <div class="text-right">
              {{-- TO-DO: Replace ID with Auth::id() --}}
              <a href="{{ route('profile.edit', ['id' => 1])}}" class="btn btn-light btn-sm" type="button">
                <i class="material-icons">edit</i>
              </a>
            </div>
          </div>
        </card-basic>

        <card-basic title="Photos I've Sent" class="mt-4">
          <div class="jumbotron rounded-0">
            {{-- Images --}}
          </div>
          <template>
            <a href="{{ route('photos.send') }}" class="btn btn-primary w-100 py-2 text-uppercase">Send Photos</a>
          </template>
        </card-basic>
      </div>
    </div>

  </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app.index')

@section('content')
  <div class="container p-3 p-lg-5">

    <div class="row">
      {{-- Sidebar --}}
      <div class="col-lg-3">
        @include('components.sidebar')
      </div>
      {{-- Main Content --}}
      <div class="col-lg-9">
        <card-basic title="Showing Profile of {{ '<User>' }}">
          card
        </card-basic>
      </div>
    </div>

  </div>
@endsection